### ISSUE TITLE
PMs

### ISSUE THREAD

**Issue by singiamtel** [singiamtel/PS-cord#2]
They should work like rooms, but separated both visually and in the code's logic

**Comment by PartMan7** [comment]
Yoink

(Gimme some perms so I can assign myself)

**Comment by singiamtel** [comment]
Done. Many thanks @PartMan7!

**Comment by PartMan7** [comment]
'many thanks' weeb you're the one that did stuff after getting tired of waiting for me

Call me a nerd or something don't thank me :pout:
